slug = "the-scotsman"
title = "The Scotsman"
author = "Steph"
value = 15
description = """Dinnae even git me stairted oan mah brothers, they wee rascals cannae lea a cake alone, ah cuid [rant](rant.jpeg) aboot it fur hours."""
tags = ["classical"]
files = ["rant.jpeg"]
flag = "flag{sc0tt1sh_rag3}"
enabled = true
